apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playwright-results
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard
